/*
 * PnlDibujo.java
 *
 * Created on 14 de agosto de 2008, 02:59 PM
 */
package curso.online.java;

import java.awt.Color;
import java.awt.Cursor;
import java.awt.Graphics;

/**
 *
 * @author  jorgaf
 */
public class PnlDibujo extends javax.swing.JPanel {

    private int x;
    private int y;

    /** Creates new form PnlDibujo */
    public PnlDibujo() {
        initComponents();
        x = -1;
        y = -1;
        Cursor puntero = new Cursor(Cursor.HAND_CURSOR);
        setCursor(puntero);
    }

    @Override
    public void paint(Graphics g) {
        if (x >= 0 && y >= 0) {
            g.setColor(Color.BLUE);
            g.fillOval(x, y, 10, 10);
        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                formMouseDragged(evt);
            }
        });

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

private void formMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseDragged
    x = evt.getX();
    y = evt.getY();
    updateUI();
}//GEN-LAST:event_formMouseDragged
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
